#!/usr/bin/env python3
"""
API reference generator
Writes docs/api-reference.md from the source: every module, class, method and
function with its signature and docstring summary. Re-run after code changes:

    python3 tools/gen_api_docs.py
"""

import ast
import os

APP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(APP, "src")
OUT = os.path.join(APP, "docs", "api-reference.md")


def summary(node):
    doc = ast.get_docstring(node) or ""
    return " ".join(doc.strip().splitlines()[:1]) if doc else ""


def signature(fn):
    args = fn.args
    parts = [a.arg for a in args.posonlyargs + args.args]
    defaults = [None] * (len(parts) - len(args.defaults)) + list(args.defaults)
    out = []
    for name, default in zip(parts, defaults):
        out.append(f"{name}={ast.unparse(default)}" if default is not None else name)
    if args.vararg:
        out.append(f"*{args.vararg.arg}")
    for a, d in zip(args.kwonlyargs, args.kw_defaults):
        out.append(f"{a.arg}={ast.unparse(d)}" if d is not None else a.arg)
    if args.kwarg:
        out.append(f"**{args.kwarg.arg}")
    return f"{fn.name}({', '.join(out)})"


def constants(tree):
    names = []
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id.isupper():
                    names.append(t.id)
    return names


def document(path):
    rel = os.path.relpath(path, APP)
    tree = ast.parse(open(path).read())
    lines = [f"### `{rel}`", ""]
    if summary(tree):
        lines += [(ast.get_docstring(tree) or "").strip().replace("\n", " "), ""]
    consts = constants(tree)
    if consts:
        lines += ["Constants: " + ", ".join(f"`{c}`" for c in consts), ""]
    rows = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            bases = ", ".join(ast.unparse(b) for b in node.bases)
            rows.append(f"| class `{node.name}({bases})` | {summary(node)} |")
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    rows.append(f"| &nbsp;&nbsp;`.{signature(item)}` | {summary(item)} |")
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            rows.append(f"| `{signature(node)}` | {summary(node)} |")
    if rows:
        lines += ["| Symbol | Purpose |", "|---|---|", *rows, ""]
    return lines


def main():
    files = []
    for root, _dirs, names in os.walk(SRC):
        files += [os.path.join(root, n) for n in names if n.endswith(".py")]
    order = ["main.py", "config", "backends", "modules", "ui", "pages", "utils"]

    def key(p):
        rel = os.path.relpath(p, SRC)
        top = rel.split(os.sep)[0]
        return (order.index(top) if top in order else 99, rel)

    out = [
        "# linscanner API reference",
        "",
        "Generated by `tools/gen_api_docs.py` from the source. Don't edit by hand; re-run the tool.",
        "",
    ]
    for path in sorted(files, key=key):
        if os.path.basename(path) == "__init__.py" and os.path.getsize(path) < 200:
            continue
        out += document(path)
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(OUT, APP)} ({len(files)} files)")


if __name__ == "__main__":
    main()
